# Generated by Django 2.2 on 2020-03-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
