# Generated by Django 2.2 on 2020-03-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_auto_20200319_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
