# Generated by Django 2.2 on 2020-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_auto_20200319_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
