# Generated by Django 2.2 on 2020-03-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_articletag_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
