# Generated by Django 2.2 on 2020-03-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0016_auto_20200320_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
