# Generated by Django 2.2 on 2020-03-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0018_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
